config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :items, only: [:create, :destroy]
  end
  get 'welcome/index'
  get 'welcome/about'
  root 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :items

  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if:  :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
    @user = current_user
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @user = current_user

    if @item.save
      flash[:success] = "Item was saved."
      redirect_to current_user
    else
      flash.now[:alert] = "There was an error saving the item. Please try again."
      render :new
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
    if @item.destroy
      flash[:notice] = "\"#{@item.name.capitalize}\" is finally completed."
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error deleting the to-do item."
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for Item.new, url: user_items_path(:user_id) do |i| %>
  <%= i.text_field :name, class: 'form-control', placeholder: "Enter new to-do list item" %>
  <div class="form-group", style="padding-top:10px">
    <%= i.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="container">
  <% if current_user && current_user.items %>
    <% @user.items.each do |item| %>
      <tr>
        <td id="item_<%= item.id%>"><%= item.name.capitalize %></td>
        <td>
          <small><%= distance_of_time_in_words(Time.now, item.created_at.to_date + 7) %> remaining before deletion</small>
        </td>
        <td><%= link_to "Completed", user_item_path(@user, item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-ok, remote: true' %>
        </td>
      </tr>
    <% end %>
  <% end %>
</div>

app/views/items/index.html.erb
<h1>All Items</h1>
<% @items.each do |item| %>
  <p><%= "#{i}" %></p>
<% end %>

app/views/items/new.html.erb
<h1>New To Dos</h1>
<div>
  <%= render partial: 'form', locals { item: @item } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
      <%= link_to "Blocitoff", welcome_index_path, class: "navbar-brand" %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%= link_to "About", welcome_about_path %></li>
      </ul>
      <div class="my-2 my-lg-0">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Signed in as: <strong><%= current_user.name %></strong>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "My To-Do List", current_user, class: "dropdown-item" %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <br>
    <div class="container">
      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
      <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/items/destroy.js.erb
$("#item_<%= @item.id %>").fadeOut();

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="media-body">
    <h3 class="media-heading text-center"><%= @user.name %>'s To-Do List</h3>
  </div>
  <div>
    <%= render partial: 'items/form', locals: { item: @item } %>
    <table class="table table-hover">
      <thead>
        <th>Item Description</th>
        <th>Days Left</th>
        <th>Completed</th>
      </thead>
      <tbody>
        <%= render partial: 'items/item', locals: { item: @item} %>
      </tbody>
    </table>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Blocitoff</h1>
  <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>
  <p>
    <% if user_signed_in? %>
      <%= link_to "#{current_user.name}'s To-Do List", current_user, class: 'btn btn-link' %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: 'btn btn-link' %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to "Sign In", user_session_path, class: 'btn btn-link' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
    <% end %>
  </p>
</div>
<div class="row">
  <div class="col-md-4">
   <h2>Get Organized!</h2>
     <p>Add items to your to-do list.<i class="fa fa-camera-retro"></i></p>
  </div>
  <div class="col-md-4">
   <h2>Be Productive!</h2>
   <p>Finish your task in 7 days. Mark as completed and your item gets taken off your list.</p>
  </div>
  <div class="col-md-4">
   <h2>Declutter</h2>
   <p>No time? No problem, <strong>Blocitoff</strong> offers decluttering. Your item will disappear after a week.</p>
  </div>
</div>